import com.example.nexusbank.buildlogic.libs
import io.gitlab.arturbosch.detekt.extensions.DetektExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.withType
import org.jlleitschuh.gradle.ktlint.KtlintExtension

/**
 * Applies Detekt + ktlint with a project-wide configuration so every module
 * is linted/formatted the same way without each `build.gradle.kts` having to
 * opt in.
 *
 * - Detekt with the `detekt-formatting` ruleset (wraps ktlint's checks).
 * - ktlint-gradle for `ktlintCheck` / `ktlintFormat` tasks.
 * - Shared config at `<root>/config/detekt/detekt.yml` (auto-generated by
 *   `./gradlew detektGenerateConfig` if missing).
 *
 * Applied automatically by `nexusbank.android.application`,
 * `nexusbank.android.library`, and `nexusbank.jvm.library`. You normally
 * never apply this plugin directly.
 */
class CodeQualityConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) = with(target) {
        with(pluginManager) {
            apply("io.gitlab.arturbosch.detekt")
            apply("org.jlleitschuh.gradle.ktlint")
        }

        extensions.configure<DetektExtension> {
            buildUponDefaultConfig = true
            allRules = false
            config.setFrom(rootProject.files("config/detekt/detekt.yml"))
            baseline = rootProject.file("config/detekt/baseline.xml")
            parallel = true
            ignoreFailures = false
        }

        extensions.configure<KtlintExtension> {
            version.set("1.3.1")
            android.set(true)
            ignoreFailures.set(false)
            enableExperimentalRules.set(false)
            filter {
                exclude { it.file.path.contains("generated/") }
                exclude { it.file.path.contains("build/") }
            }
            reporters {
                reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.PLAIN)
                reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.CHECKSTYLE)
            }
        }

        dependencies {
            add("detektPlugins", libs().findLibrary("detekt-formatting").get())
        }

        // Make every detekt task produce SARIF for CI integration.
        tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
            jvmTarget = "11"
            reports {
                html.required.set(true)
                xml.required.set(true)
                sarif.required.set(true)
                md.required.set(false)
                txt.required.set(false)
            }
        }
        tasks.withType<io.gitlab.arturbosch.detekt.DetektCreateBaselineTask>().configureEach {
            jvmTarget = "11"
        }
    }
}
